package fr.insarouen.inforep.harbormaster.common;

public enum Case {
	VIDE,
	TERRE,
	PORT_BRUN,
	PORT_VERT,
	TERRE_DIAGONALE_BAS_DROITE,
	TERRE_DIAGONALE_HAUT_DROITE,
	TERRE_DIAGONALE_BAS_GAUCHE,
	TERRE_DIAGONALE_HAUT_GAUCHE
}
